# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: rostemplate-gh-pages

jobs:
  rostemplate-gh-pages:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      THUNDERFOREST_API_KEY: ${{ secrets.THUNDERFOREST_API_KEY }}
      MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}

    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          install-r: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages:
            local::.
            any::cli
            any::rcmdcheck
            any::pkgdown
            any::reactable
            any::rnaturalearth
            any::tidyverse
            dieghernan/pkgdev
            ropenspain/rostemplate
            ropensci/rnaturalearthhires
          needs: website

      - name: Deploy package
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, run_dont_run = TRUE)'

